name: diffusionmagic-env
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.3
  - pytorch-cuda=11.7
  - pytorch=2.0.0
  - torchvision=0.15.0
  - numpy=1.19.2
  - pip:
      - accelerate==0.17.1
      - diffusers==0.14.0
      - gradio==3.17.1
      - safetensors==0.2.8
      - scipy==1.10.0
      - transformers==4.26.0
      - pydantic==1.10.4
      - mypy==1.0.0
      - black==23.1.0
      - flake8==6.0.0
      - markupsafe==2.0.1
      - opencv-contrib-python==4.7.0.72
      - controlnet-aux==0.0.1